# Generated by Django 4.1.2 on 2023-01-27 01:55

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="book_order",
            field=django_mysql.models.ListCharField(
                models.CharField(max_length=10), default=[], max_length=66, size=6
            ),
            preserve_default=False,
        ),
    ]
