# Generated by Django 4.1.2 on 2023-01-30 02:59

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile_book_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="book_order",
            field=django_mysql.models.ListCharField(
                models.CharField(max_length=10), max_length=66, null=True, size=6
            ),
        ),
    ]
