# Generated by Django 4.1.2 on 2023-01-30 03:02

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_profile_book_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="book_order",
            field=django_mysql.models.ListCharField(
                models.CharField(max_length=10, null=True),
                default=1,
                max_length=66,
                size=6,
            ),
            preserve_default=False,
        ),
    ]
