# Generated by Django 4.1.2 on 2023-02-06 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0004_alter_profile_book_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="book_order",
            field=django_mysql.models.ListCharField(
                models.CharField(blank=True, max_length=100, null=True),
                max_length=66,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
