# Generated by Django 4.1.2 on 2023-02-10 02:05

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_profile_book_order_alter_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="book_order",
            field=django_mysql.models.ListCharField(
                models.CharField(blank=True, max_length=100, null=True),
                blank=True,
                max_length=66,
                null=True,
                size=None,
            ),
        ),
    ]
